### ISSUE TITLE
Is the upstream/downstream concept relevant for packages or for source code?

### ISSUE THREAD

**Issue by elsamoheg** [MohamedRadwan-DevOps/devops-step-by-step#118]
Module 8 in /source/devops-lessons-preparation.md is about packages. It has a bullet point named "Upstream source for package management" but I think the webpage and the video there are unrelated to package management. The upstream/downstream concept is related to forking of source code. It describes where it's best to make changes to the source code (in the fork vs base repo) to facilitate integrating the source code among repos at different levels of the source code hierarchy. Of course any fork or base repo can be compiled to produce a package but that's irrelevant for the package management process itself. I think it makes more sense to move the "Upstream ..." bullet point and the links under it to Module 17 after the bullet point named "Git Fork". Please advise if I missed anything.

**Comment by AndrewSeif** [comment]
upstream/downstream concept is _indeed relevant for packages_ , where as if you go through the modules you will learn the concepts of DLLs as well as package repositories, and why we use them, and that is where the concept stems from.

**Comment by elsamoheg** [comment]
The source code is the thing that can be modified upstream or downstream and the built package (DLL for example) is just a result of what happened at the source code level. The upstream/downstream decision is made at the source code level not at the package level.

**Comment by AndrewSeif** [comment]
If I create a package (DLL) and publish it in NuGet, and then built an app that requires it, then that's an example of upstream/downstream package management. 

because my app requires DLL (upstream) , and that DLL itself got a downstream. 

Another example of this is Ubuntu, Ubuntu upstream is Debian, and Ubuntu downstream is Linux Mint.

Finally, please read more about the topic, a simple google search will net alot of amazing results! 😄
