### ISSUE TITLE
Create a Q/A for the demo: create and examine Ubuntu 20.04 VM (created) from gallery

### ISSUE THREAD

**Issue by RehabAbotalep** [MohamedRadwan-DevOps/devops-step-by-step#144]

**Comment by AhalimZaki** [comment]
1. Highlight squares and numbers should by more organized.

2. Highlight squares should fit the content you are highlighting.

3. More description should be added and should be detailed and explain the picture, there is some pictures with no description at all try to be detailed as much as you can.

4. There are some filler pictures for example these two pictures don't need any interaction from the user so it's not useful to the user and it's not adding any value. 
http://devopsvisionsqa.mohamedradwan.com/?qa=blob&qa_blobid=14942278209345637784
http://devopsvisionsqa.mohamedradwan.com/?qa=blob&qa_blobid=7061947678383599333

5. Try to avoid adding two or three pictures in a row without a specific description 

6. When saving a picture consider not leaving any dots on the picture by the edit tools since it's noticeable on all the pictures.

@fadysaad66

**Comment by RehabAbotalep** [comment]
@fadysaad66 Are you okay with all the points provided by @AhalimZaki?

**Comment by AhalimZaki** [comment]
@fadysaad66 
Steps numbers should be to the right or left of the Highlight square, this is shown in the guidelines 
https://devopsvisionsqa.mohamedradwan.com/?qa=501/what-are-the-guidelines-should-follow-when-writing-down-demo

For example, this is the picture you provided  in the demo : 
http://devopsvisionsqa.mohamedradwan.com/?qa=blob&qa_blobid=1763634787391666972

And this is another picture in Mohammed Eid demo 
http://devopsvisionsqa.mohamedradwan.com/?qa=blob&qa_blobid=7220815745475342321

You  can notice the difference.

**Comment by RehabAbotalep** [comment]
@AhalimZaki Please confirm your final review.

**Comment by AhalimZaki** [comment]
@fadysaad66 
I have edited some minor stuff punctuation and an image, since you mentioned I can change the VM settings , I changed the wrapped square to wrap Memory, Processor,Hard disk as mentioned above the picture you was highlighting only the ram.
http://devopsvisionsqa.mohamedradwan.com/?qa=blob&qa_blobid=4383034792312616531

While you're writing down the script for steps you have to make in consideration for the punctuation of capitalizing the first letter and "." at the end, keep that in mind for future content.

Also, one thing I noticed and need to mention and need your attention about it is when you write down a demo I notice that there so many spaces between every line and picture and by spaces I mean Alot of Usage of "Space bar" on Q/A it's better to use "Enter" to make a new line and post the new picture and unassign bullet points if needed as a reviewer when I wanted to edit something on your answer it took my a lot of time to adjust some stuff because they usage of plenty of space between pic and line itself when deleting it give me a feeling that I removed something because it shouldn't be done like this. 

Also by following our guidelines, it has been mentioned that You should make Kareem assignment Question as a reference and you should start structuring it yourself if needed, Bullet points on so many steps is not recommended when writing down a step-by-step demo.

@RehabAbotalep I have no further comments but I need your follow-up review on the Q/A itself "space-bar" spam usage.

**Comment by RehabAbotalep** [comment]
@fadysaad66 @AhalimZaki 
1- There is no consistency in the space between every step and its following image, sometimes there is one line, sometimes 2 lines, and sometimes no line, please keep the consistency.
2- In the last step (Start exploring Ubuntu) the description is not proper with its following image.
3- No consistency in the font size used.

**Comment by RehabAbotalep** [comment]
@fadysaad66 @AhalimZaki I have made some edits in the description of the steps, kindly check them.
@MohamedRadwan-DevOps Your review, plz.
http://devopsvisionsqa.mohamedradwan.com/?qa=506/what-are-the-steps-create-examine-ubuntu-created-from-gallery
