### ISSUE TITLE
Bug microsoft-devops-faq.md

### ISSUE THREAD

**Issue by naja-ahmed** [MohamedRadwan-DevOps/devops-step-by-step#639]
Issues description:

1-The certification image does not appear.

2-Course prerequisites link (line 24 in microsoft-devops-faq.md)
When attempting to access the Course prerequisites link, it leads to 404 - page not found.

Navigate to Mastering Microsoft DevOps Solutions (Get Certified)
		Course FAQ 
Scroll down to line 24 for the "Course prerequisites" link.

**Comment by naja-ahmed** [comment]
Please , assign to me .

**Comment by ShereenS** [comment]
@naja-ahmed Could you please change the link to redirect to [mastering-devops-certification.png](https://github.com/MohamedRadwan-DevOps/devops-step-by-step/blob/main/source/images/mics/mastering-devops-certification.png) instead of [404 error](https://github.com/MohamedRadwan-DevOps/devops-step-by-step/blob/main/source/mastering-microsoft-devops-solutions/images/mics/mastering-devops-certification.png)

**Comment by naja-ahmed** [comment]
Done for the 2 issues i wrote.
Sorry , i could not find a link called "certification" , would you please help me ?

**Comment by ShereenS** [comment]
@naja-ahmed I appreciate your efforts, for the certification link issue:

1.  Navigate to Mastering Microsoft DevOps Solutions (Get Certified)
2. Go to Course FAQ at line 14 like the attached image 

 ![image](https://github.com/MohamedRadwan-DevOps/devops-step-by-step/assets/23116283/3ad4ee3d-1177-4da5-999c-3bc71570d5a5)
